# In Docker
# - TEST_POSTGRES_URI=postgres://bookshelf:bookshelf@postgres/
# Outside Docker
# - TEST_POSTGRES_URI=postgres://bookshelf:bookshelf@localhost:5432/

version: '3.8'

services:
  postgres:
    container_name: bookshelf_backend_rest_container_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-bookshelf}
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
