version: '3.8'

services:
  database:
    container_name: bookshelf_server_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-unicorn_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-magical_password}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-rainbow_database}
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  database-data: # named volumes can be managed easier using docker-compose

